version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    working_dir: /code
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
